// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGJl4PAy_gimylpoEpp5avMXYjqowTDPE',
    appId: '1:843254746575:web:5b73c02b137c365f9396ba',
    messagingSenderId: '843254746575',
    projectId: 'flutterapp-3d291',
    authDomain: 'flutterapp-3d291.firebaseapp.com',
    storageBucket: 'flutterapp-3d291.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtZtJh6avLPntuk0wZKpeZcPfBDIhyj4',
    appId: '1:843254746575:android:5bcd3c5acd34ba7c9396ba',
    messagingSenderId: '843254746575',
    projectId: 'flutterapp-3d291',
    storageBucket: 'flutterapp-3d291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzQuRWDyYnhGjfRUg5Fo3bqo9D_ZIzuEY',
    appId: '1:843254746575:ios:ff5bf4facdcd921e9396ba',
    messagingSenderId: '843254746575',
    projectId: 'flutterapp-3d291',
    storageBucket: 'flutterapp-3d291.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzQuRWDyYnhGjfRUg5Fo3bqo9D_ZIzuEY',
    appId: '1:843254746575:ios:ff5bf4facdcd921e9396ba',
    messagingSenderId: '843254746575',
    projectId: 'flutterapp-3d291',
    storageBucket: 'flutterapp-3d291.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGJl4PAy_gimylpoEpp5avMXYjqowTDPE',
    appId: '1:843254746575:web:e181ba9a70254c499396ba',
    messagingSenderId: '843254746575',
    projectId: 'flutterapp-3d291',
    authDomain: 'flutterapp-3d291.firebaseapp.com',
    storageBucket: 'flutterapp-3d291.firebasestorage.app',
  );
}
